### ISSUE TITLE
[BLINKING ANIMATION] Audible time reminder

### ISSUE THREAD

**Issue by danstsx** [Parakoos/sgt-cp#1]
I think blinking is too fast and also they're not increasing.

First time reminder (one blink)
Second reminder (two blinks)
Third reminder and nexts ones (three blinks)

Now its blinking only once no matter wich reminder is.

**Comment by Parakoos** [comment]
I hope this is fixed in 97541edbf7bd04c278072c2e58388a0e853c32dc
