### ISSUE TITLE
[COMET ANIMATION] Speed not working

### ISSUE THREAD

**Issue by danstsx** [Parakoos/sgt-cp#3]
This setting doesnt seem to take any effect: 

COMET_PIXEL_PER_SEC = 10

The way it is right now is very slow, and changing it to 100 or 1, didn't make any difference.

**Comment by Parakoos** [comment]
This should be fixed in 97541edbf7bd04c278072c2e58388a0e853c32dc. Look at the top of ``view_table_outline.py`` to see available settings to put into settings.toml. In this case, it would be

``
TABLE_COMET_SPEED_PPS = 10
``
