### ISSUE TITLE
Simultaneous Turns Function

### ISSUE THREAD

**Issue by danstsx** [Parakoos/sgt-cp#4]
The main idea here is to be able to toggle sim. turns on and off with a shortcut (I believe the "undo" function can be removed from the table shortcuts and be available only on the master control, then we can use the triple press and hold to start a sim. turn).

When the Sim. Turn is activated through the shortcut, it would be useful to create a way to enable/disable each player. One suggestion is for the player to press and hold the button to leave that simultaneous turn (or rejoin if they leave by mistake). This way, it’s easier to organize who will participate in each sim. turn.

Two Scenarios:

1. In the first scenario, we have a racing game where, after everyone has finish their turn, there is an admin turn to organize the new play order (whoever is in the lead goes first). After that here is a sim.turn where everyone must choose the cards they will play in that turn. In this case, everyone will always participate in the sim. turn, so no extra actions needed.

2. In the second scenario, we have a war game where the war phase has “x” battles (the number increases as the game progresses so its hard to program in advance). In this phase, only some players participate in each battle. So, in battle A, we have players 1 and 2, and in battle B, we have players 2 and 3. When we start the first simultaneous turn in the first few seconds, players 3, 4, and 5 press and hold the button to leave that battle, making the timer run only for players 1 and 2 until the battle ends. Then battle B... so players 1, 4, and 5 will need to press and hold to leave and so on.
Regardless of the game, it is helpful to keep the "end sim. turn" function for players in the sim. turn instead of just turn them off like players 3, 4 and 5 did in the first battle. This is useful, for example, to show Player1 that everyone that was in battle has passed already, and only him need to play for the game to proceed. Also everyone can easily check who was active too.

I think the best part will be able to "script" those sim. turns using templates... 
Even for games that don't require a specific sim. turn mechanic, I can envision a scenario where we can integrate simultaneous turns to regain everyone's attention to the game. Something like: "Is everyone ready to start the next round? Then prepare your cards or wahtever and confirm when you’re ready to begin a next round."

**Comment by danstsx** [comment]
We make a draft on Terraforming mars, so we take 4 consecutive sim. turns between each round start. This setting would be perfect to check whos still thinking or whos already passed the cards.

**Comment by Parakoos** [comment]
I think it is important to keep in mind that even though an element of a
game could be timed, it may not mean that it should be timed. E.g. the 4x
draft in TM. If the draft is already feels 'snappy' then it may be better
to be left as just 'Admin time'. But if it suffers from slow outdrawn
selections, then maybe using Sim.Turns is the way to go

**Comment by Parakoos** [comment]
SGT has no concept of 'dropping out' of a Sim.Turn once it is under-way. So I don't really want to add it to the remote control API if I can help it. 

My suggestion is that to start a sim turn, you press and hold somehow.  (2 times?  3 times? I don't care) 

If you release right away, you start a sim turn that involves all players. 

To limit the sim turn to a subset of players, you press and hold,  and keep holding while the participating players press and hold their buttons. Then the initiating player release their button to start the sim turn.

Thoughts?

**Comment by danstsx** [comment]
> To limit the sim turn to a subset of players, you press and hold, and keep holding while the participating players press and hold their buttons. Then the initiating player release their button to start the sim turn.

Yeah that works! I just need a quick way to set specific players to different and subsequents sim. turns.
And when a sim. turn happens to be on a script of a game (Like the "1*" you suggested) everyone on the game will participate of that sim. turn by default.

**Comment by Parakoos** [comment]
From a table-perspective, is this feature done? I know there may be some SGT changes for scripting SimTurns, but in terms of being able to initiate SimTurns from the table, is this done?

**Comment by danstsx** [comment]
Yes! Its done and working great
